-- DROP DATABASE IF EXISTS bnbbookingservice;
DROP USER IF EXISTS `bnbbooking`@`%`;
CREATE DATABASE IF NOT EXISTS bnbbookingservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `bnbbooking`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `bnbbookingservice`.* TO `bnbbooking`@`%`;
FLUSH PRIVILEGES;
